{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww13440\viewh7800\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 filebeat.inputs:\
- type: filestream\
  enabled: false\
  paths:\
    - /var/log/*.log\
filebeat.config.modules:\
  path: $\{path.config\}/modules.d/*.yml\
  reload.enabled: false\
setup.template.settings:\
  index.number_of_shards: 1\
setup.kibana:\
  host: "10.250.0.4:5601"\
output.logstash:\
  hosts: ["localhost:5044"]\
processors:\
  - add_host_metadata:\
    when.not.contains.tags: forwarded\
  - add_cloud_metadata: ~\
  - add_docker_metadata: ~\
  - add_kubernetes_metadata: ~\
}